import Foundation

public struct ApplicationIdentity: Hashable, Codable, Sendable {
    public let bundleIdentifier: String
    public let teamIdentifier: String
    public let signingIdentifier: String

    public init(bundleIdentifier: String, teamIdentifier: String, signingIdentifier: String) {
        self.bundleIdentifier = bundleIdentifier
        self.teamIdentifier = teamIdentifier
        self.signingIdentifier = signingIdentifier
    }
}

public enum SourceConfidence: String, Codable, Sendable {
    case unknown
    case inferredStableForeground
}

public struct SourceObservation: Hashable, Codable, Sendable {
    public let identity: ApplicationIdentity?
    public let confidence: SourceConfidence

    public init(identity: ApplicationIdentity?, confidence: SourceConfidence) {
        self.identity = identity
        self.confidence = confidence
    }
}

public struct PasteboardEventMetadata: Hashable, Codable, Sendable {
    public let changeCount: Int
    public let declaredTypeIdentifiers: [String]
    public let source: SourceObservation
    public let capturePauseActive: Bool

    public init(
        changeCount: Int,
        declaredTypeIdentifiers: [String],
        source: SourceObservation,
        capturePauseActive: Bool
    ) {
        self.changeCount = changeCount
        self.declaredTypeIdentifiers = declaredTypeIdentifiers
        self.source = source
        self.capturePauseActive = capturePauseActive
    }
}

public struct CapturePolicy: Hashable, Codable, Sendable {
    public let consentGranted: Bool
    public let ignoredApplications: Set<ApplicationIdentity>
    public let privateCopyMarkerTypeIdentifier: String
    public let confidentialTypeIdentifiers: Set<String>
    public let supportedPrimaryTextTypeIdentifiers: Set<String>

    public init(
        consentGranted: Bool,
        ignoredApplications: Set<ApplicationIdentity>,
        privateCopyMarkerTypeIdentifier: String,
        confidentialTypeIdentifiers: Set<String>,
        supportedPrimaryTextTypeIdentifiers: Set<String>
    ) {
        self.consentGranted = consentGranted
        self.ignoredApplications = ignoredApplications
        self.privateCopyMarkerTypeIdentifier = privateCopyMarkerTypeIdentifier
        self.confidentialTypeIdentifiers = confidentialTypeIdentifiers
        self.supportedPrimaryTextTypeIdentifiers = supportedPrimaryTextTypeIdentifiers
    }

    public static func standard(
        consentGranted: Bool,
        ignoredApplications: Set<ApplicationIdentity>
    ) -> Self {
        Self(
            consentGranted: consentGranted,
            ignoredApplications: ignoredApplications,
            privateCopyMarkerTypeIdentifier: "com.andrewdongminyoo.clipboardkeyboard.private-copy",
            confidentialTypeIdentifiers: [
                "com.agilebits.onepassword",
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
            ],
            supportedPrimaryTextTypeIdentifiers: [
                "public.utf8-plain-text",
                "public.plain-text",
                "net.daringfireball.markdown",
                "public.rtf",
                "public.html",
            ]
        )
    }
}

public enum PrivacyDropReason: String, Codable, Sendable {
    case consentNotGranted
    case privateCopyMarker
    case confidentialType
    case capturePaused
    case unknownSource
    case ignoredApplication
    case unsupportedPrimaryTextType
}

public enum PrivacyDecision: Equatable, Sendable {
    case drop(PrivacyDropReason)
    case authorizeRead(changeCount: Int)
}

public enum RetentionClass: String, Codable, Sendable {
    case ignored
    case systemEphemeral
    case localHistory
    case pinned
}

public struct ClipMetadata: Hashable, Codable, Sendable {
    public let id: UUID
    public let capturedAt: Date
    public let byteCount: Int
    public let representationKinds: [String]
    public let keyedDigest: Data
    public let sourceConfidence: SourceConfidence
    public let isPinned: Bool

    public init(
        id: UUID,
        capturedAt: Date,
        byteCount: Int,
        representationKinds: [String],
        keyedDigest: Data,
        sourceConfidence: SourceConfidence,
        isPinned: Bool
    ) {
        self.id = id
        self.capturedAt = capturedAt
        self.byteCount = byteCount
        self.representationKinds = representationKinds
        self.keyedDigest = keyedDigest
        self.sourceConfidence = sourceConfidence
        self.isPinned = isPinned
    }
}
